version: '3.8'
services:
  fuse-tool-pca:
    container_name: fuse-tool-pca
    build:
        context: .
    restart: always
    env_file: .env
    ports:
        - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - $PWD/config/config.json:/app/config.json
    networks:
      - tool_pca_network

networks:
  tool_pca_network:
    name: ${CONTAINER_NETWORK}
    external: true

